### PR TITLE
Add tests for the core app

### PR DESCRIPTION
**Pull request by jmaupetit**
- [x] Add `pytest` dependency
- [x] Add [django-configurations](http://django-configurations.readthedocs.io/en/latest/)
- [x] Add `Base`/`Development`/`Test` settings
- [x] Configure `pytest`
- [x] Add tests for the `HomeView`
- [x] Add & configure `pytest-cov` dependency
- [x] Add documentation about running tests
- [x] Add & configure `flake8` dependency
- [x] Add documentation about code linting

### CODE REVIEW

**Comment by thomasdenecker** [comment]
Juste a little question. Is it possible to launch `pytest` at this stage?

**Comment by jmaupetit** [comment]
Yes! Take a look at the `README.md` diff

**Comment by thomasdenecker** [comment]
I am sorry! I did not see... :S

**Comment by jmaupetit** [comment]
Danke!

**Pull request merged**
