### PR TITLE
Add core models

### PR DESCRIPTION
**Pull request by jmaupetit**
This PR is preliminary work on #11.

- [x] Add `core` app models & migrations
- [x] Add `data` app models & migrations
- [x] Squash migrations

The following items will be postponed to future PRs to ease PR reviews:

- Add models to Django admin
- Add factories for models
- Add unit tests for models

### CODE REVIEW

**Comment by jmaupetit** [comment]
I've dropped previous migrations. At this stage, keeping those migrations would not make sense (data modeling was still a WIP). Starting from now, migrations will be maintained and regularly [squashed](https://docs.djangoproject.com/en/1.11/ref/django-admin/#squashmigrations).

To fix your issue, you need to remove your draft database and perform migrations:

```bash
$ rm db.sqlite3
$ make migrate-db
```

**Comment by jmaupetit** [comment]
1. Can you execute the following command and tell me if an error is raised (or else if a dot file is printed in standard output)?

```bash
$ pipenv run -- ./manage.py graph_models -E core data -X AbstractUser,TaggedModel,MPTTModel,TagModel
```

2. Can you tell me which version of Graphviz you have installed by pasting the output of the following command:

```bash
$ dot -V
```

I am using `dot - graphviz version 2.40.1 (20161225.0304)`

**Comment by thomasdenecker** [comment]
For `$ pipenv run -- ./manage.py graph_models -E core data -X AbstractUser,TaggedModel,MPTTModel,TagModel `:

```
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Warning: There was an unexpected error while activating your virtualenv. Continuing anyway…
digraph model_graph {
  // Dotfile by Django-Extensions graph_models
  // Created: 2017-10-11 15:53
  // Cli Options: -E core data -X AbstractUser,TaggedModel,MPTTModel,TagModel

  fontname = "Helvetica"
  fontsize = 8
  splines  = true

  node [
    fontname = "Helvetica"
    fontsize = 8
    shape = "plaintext"
  ]

  edge [
    fontname = "Helvetica"
    fontsize = 8
  ]

  // Labels


  apps_core_models_Species [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Species
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">reference</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">CharField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_Strain [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Strain
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">species</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">CharField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_OmicsUnitType [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    OmicsUnitType
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">CharField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_OmicsUnit [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    OmicsUnit
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">reference</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">strain</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">type</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">status</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">PositiveSmallIntegerField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_Pixel [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Pixel
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">analysis</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">omics_unit</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">quality_score</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">FloatField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">value</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">FloatField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_Tag [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Tag<BR/>&lt;<FONT FACE="Helvetica Italic">TagModel</FONT>&gt;
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">AutoField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Italic">count</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Italic">IntegerField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Italic">name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Italic">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">protected</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">BooleanField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Italic">slug</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Italic">SlugField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_Experiment [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Experiment<BR/>&lt;<FONT FACE="Helvetica Italic">TaggedModel</FONT>&gt;
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">omics_area</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">created_at</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">DateTimeField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">released_at</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">DateField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">saved_at</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">DateTimeField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_Analysis [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Analysis<BR/>&lt;<FONT FACE="Helvetica Italic">TaggedModel</FONT>&gt;
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">pixeler</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">created_at</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">DateTimeField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">notebook</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">FileField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">saved_at</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">DateTimeField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">secondary_data</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">FileField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_OmicsArea [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    OmicsArea<BR/>&lt;<FONT FACE="Helvetica Italic">MPTTModel</FONT>&gt;
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Bold">parent</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Bold">TreeForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">level</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">PositiveIntegerField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">lft</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">PositiveIntegerField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">rght</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">PositiveIntegerField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">tree_id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">PositiveIntegerField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_core_models_Pixeler [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Pixeler<BR/>&lt;<FONT FACE="Helvetica Italic">AbstractUser</FONT>&gt;
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Italic">date_joined</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Italic">DateTimeField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">email</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">EmailField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">first_name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">is_active</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">BooleanField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">is_staff</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">BooleanField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">is_superuser</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">BooleanField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">last_login</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">DateTimeField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">last_name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica Italic">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Italic">password</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Italic">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Italic">username</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Italic">CharField</FONT>
    </TD></TR>
  
    </TABLE>
    >]




  apps_data_models_Repository [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Repository
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica ">name</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica ">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">url</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">URLField</FONT>
    </TD></TR>
  
    </TABLE>
    >]

  apps_data_models_Entry [label=<
    <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
    <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
    <FONT FACE="Helvetica Bold" COLOR="white">
    Entry
    </FONT></TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">id</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">UUIDField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT FACE="Helvetica Bold">repository</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT FACE="Helvetica Bold">ForeignKey (id)</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">description</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">TextField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">identifier</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">CharField</FONT>
    </TD></TR>
  
    <TR><TD ALIGN="LEFT" BORDER="0">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">url</FONT>
    </TD><TD ALIGN="LEFT">
    <FONT COLOR="#7B7B7B" FACE="Helvetica ">URLField</FONT>
    </TD></TR>
  
    </TABLE>
    >]




  // Relations

  apps_core_models_Species -> apps_data_models_Entry
  [label="reference (species)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_Strain -> apps_core_models_Species
  [label="species (strain)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_OmicsUnit -> apps_data_models_Entry
  [label="reference (omicsunit)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_OmicsUnit -> apps_core_models_Strain
  [label="strain (omics_unit)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_OmicsUnit -> apps_core_models_OmicsUnitType
  [label="type (omics_unit)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_Pixel -> apps_core_models_OmicsUnit
  [label="omics_unit (pixel)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_Pixel -> apps_core_models_Analysis
  [label="analysis (pixel)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_Experiment -> apps_core_models_OmicsArea
  [label="omics_area (experiment)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_Experiment -> apps_data_models_Entry
  [label="entries (experiment)"] [arrowhead=dot arrowtail=dot, dir=both];

  apps_core_models_Experiment -> apps_core_models_Tag
  [label="tags (experiment)"] [arrowhead=dot arrowtail=dot, dir=both];

  apps_core_models_Analysis -> apps_core_models_Pixeler
  [label="pixeler (analysis)"] [arrowhead=none, arrowtail=dot, dir=both];

  apps_core_models_Analysis -> apps_core_models_Experiment
  [label="experiments (analysis)"] [arrowhead=dot arrowtail=dot, dir=both];

  apps_core_models_Analysis -> apps_core_models_Tag
  [label="tags (analysis)"] [arrowhead=dot arrowtail=dot, dir=both];

  apps_core_models_OmicsArea -> apps_core_models_OmicsArea
  [label="parent (children)"] [arrowhead=none, arrowtail=dot, dir=both];
  django_contrib_auth_models_Group [label=<
  <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
  <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
  <FONT FACE="Helvetica Bold" COLOR="white">Group</FONT>
  </TD></TR>
  </TABLE>
  >]
  apps_core_models_Pixeler -> django_contrib_auth_models_Group
  [label="groups (user)"] [arrowhead=dot arrowtail=dot, dir=both];
  django_contrib_auth_models_Permission [label=<
  <TABLE BGCOLOR="palegoldenrod" BORDER="0" CELLBORDER="0" CELLSPACING="0">
  <TR><TD COLSPAN="2" CELLPADDING="4" ALIGN="CENTER" BGCOLOR="olivedrab4">
  <FONT FACE="Helvetica Bold" COLOR="white">Permission</FONT>
  </TD></TR>
  </TABLE>
  >]
  apps_core_models_Pixeler -> django_contrib_auth_models_Permission
  [label="user_permissions (user)"] [arrowhead=dot arrowtail=dot, dir=both];


  apps_data_models_Entry -> apps_data_models_Repository
  [label="repository (entry)"] [arrowhead=none, arrowtail=dot, dir=both];


}
```
And for `dot -V` :

```
dot - graphviz version 2.36.0 (20140111.2315)
```

**Comment by jmaupetit** [comment]
Can you update your `graphviz` installation? 

If it has been install with [homebrew](https://brew.sh/):

```bash
$ brew upgrade graphviz
```

**Comment by willdurand** [comment]
Hi @thomasdenecker, for large outputs, you can use the `<details>` HTML tag. This is what I've done by editing your last comment 😉

**Comment by thomasdenecker** [comment]
`brew upgrade graphviz`: 

```
Error: graphviz not installed
```
So, to install the library :
```
$ brew install graphviz
$ brew link --overwrite graphviz
```
Now, the command lines `pipenv run -- ./manage.py graph_models -E core data -X AbstractUser,TaggedModel,MPTTModel,TagModel | dot -T pdf -o ./docs/pixel-db.pdf` works.

**Pull request merged**
