### PR TITLE
Add checksum to importation template

### PR DESCRIPTION
**Pull request by jmaupetit**
## Purpose

To communicate with Pixel's users and ensure that they are using the latest non-corrupted version of the template, we need to provide a version number and a sha256 checksum of generated template.

## Proposal

As an XLSX file is a zip archive (embedding varying metadata), we cannot provide a unique sha256 checksum corresponding to a template version (and a database state). Hence, the XLSX template's sha256 checksum is calculated for every generated template and stored in user's session. 

As we need a unique identifier for a specific version of the template, we calculate a version number as follow: concatenate all zipped files CRC-32 and hash concatenated CRCs with sha256. This version number is also stored in user's session.

After downloading the template, an action button invites the user to reveal the file's checksum and version.

## Sneak peek

screenshot-2017-11-14 download submission template

screenshot-2017-11-14 download submission template 1

### CODE REVIEW

**Comment by pierrepo** [comment]
Sorry I don't get it. What is it used for, humans or computers? Could you provide (in comments) a simple use-case?

**Comment by jmaupetit** [comment]
We provide a sha256 checksum of the XLSX template that users willing to import new data will download. Once downloaded, they will need to check that the file they downloaded as the same checksum as the one referenced in the download step. Like the old times when we were downloading  OS iso images. Do you remember these days?

**Comment by pierrepo** [comment]
So far so good. But then, how the user will check that the checksum of the template he has just downloaded is correct?

**Comment by jmaupetit** [comment]
We need to add contextual help to explain how. For Unix systems it's a matter of a single command line like `$ shasum -a 256 <xlsx_file>`. For windows users, I've seen that there is also a native tool for that: https://superuser.com/questions/245775/is-there-a-built-in-checksum-utility-on-windows-7/898377#898377

Are you experimented with such windows tool?

**Comment by pierrepo** [comment]
OK. I know how to use `shaxxsum` tools but you said 

> we cannot provide a unique sha256 checksum corresponding to a template version

so how the end-user can  

> concatenate all zipped files CRC-32 and hash concatenated CRCs with sha256

with a simple tool, on his own workstation?

I'm a bit lost of what exactly the user will have to do.

**Comment by pierrepo** [comment]
So I think I started to figure out how things are working.

The calculated checksum is a very good idea. It will ensure the downloaded template is the correct one.

But what about the version number? Why do we need one? Why the use of CRC? Shouldn't we expect a more semantic version number (i.e 1.3 or even 1) ?

**Comment by gaellelelandais** [comment]
Hi there,
Do you think it is really important to perform a checksum on the excel file ? I guess it is more important to do that on the secondary data file and the pixel files. Checksum information for these files (very important indeed) could be part of the information inserted in the meta.xls file ?

**Comment by pierrepo** [comment]
@gaellelelandais could you please give more details with the procedure you started to describe? I think we have to agree on a typical use-case before doing any implementation.

To ease the discussion, could we agree on a naming convention for files? E.g: `meta.xlsx` for meta information file (downloaded as a template from the website), `data1.xlsx` for data...

**Comment by jmaupetit** [comment]
@gaellelelandais you are totally right. We should ask users to add checksums of secondary data files + notebook to ensure their integrity. I'll open an issue for this.

**Pull request merged**
