### PR TITLE
Add stack overview

### PR DESCRIPTION
**Pull request by thomasdenecker**
- [x] Create a stack overview

### CODE REVIEW

**Comment by gaellelelandais** [comment]
Nice work ! Still, it seems to me that a figure legend would be necessary to really understand this schema. Maybe this is because I am not familiar enough with the tools you are citing, but for instance, I don't see the difference between major and minor tools. What kind of dependancy do they share ?

**Comment by jmaupetit** [comment]
Another remark: which tool has been used to generate this picture? Can you also provide the source file?

**Comment by jmaupetit** [comment]
Should we close this PR and open a new one with the `Add_stack_overview_SVG_format` branch? If you do so @thomasdenecker, don't forget to cite this PR #62 to link our discussion to your new PR.

**Comment by thomasdenecker** [comment]
Yes. Please @gaellelelandais and @pierrepo, can you validate your review?

**Comment by gaellelelandais** [comment]
I like this last version. Only the figure legend is missing. We discussed this last point @thomasdenecker and I this afternoon.... and we concluded that we really need your help @jmaupetit !

**Comment by pierrepo** [comment]
After my last review, I was really uncomfortable with my understanding of the whole process in Pixel. So I tried to think more in terms of where (providers) and who (doers) than in term of when. Here what I did:
[stack_overview_2.pdf](https://github.com/Candihub/pixel/files/1476564/stack_overview_2.pdf)

What exactly is doing CircleCI is still unclear to me. For instance:

- Is CircleCI really compiling the front-end? If yes, why the compiled front-end cannot be embedded in the Pixel container (do avoid to call also the Node container in the Production server)?
- What does CircleCI test? Only the Python functions? Also the connection to the PostreSQL database?

**Comment by jmaupetit** [comment]
@pierrepo here is a review of your schema:

pixel_stack_fix

> Is CircleCI really compiling the front-end? If yes, why the compiled front-end cannot be embedded in the Pixel container (do avoid to call also the Node container in the Production server)?

Circle-CI compiles the front-end and embeds compiled styles in Pixel's container so that the production server does not need a node container. You can see this in CircleCI configuration: https://github.com/Candihub/pixel/blob/master/.circleci/config.yml#L31

Styles are compiled in the `frontend-build` job and stored in a "temporary backup" (cache). This backup is then restored during the `backend-build` job that copies styles in the container during Pixel's container build (see https://github.com/Candihub/pixel/blob/master/Dockerfile#L38).

> What does CircleCI test? Only the Python functions? Also the connection to the PostreSQL database?

CircleCI runs python code testing using `pytest` as a test runner. In our tests, we test every single statement in our python code, this includes testing our models, views, functions, etc. Testing these lines of code requires a connection to a test database (created every time we execute the test suite). Hence you can consider that the database part is also tested.

I hope this clarifies what's behind the scene.

**Comment by jmaupetit** [comment]
@thomasdenecker I can see that something went wrong with this branch 😛 

unexpected_merge

**Comment by pierrepo** [comment]
@jmaupetit 

> I hope this clarifies what's behind the scene.

Yes very much. Thanks a lot. Your explanations are really helpful.

Why the caching of the front-end in CircleCI? Because the scss code changes less than the back-end or because its compilation is very slow?

I was not aware that in the production phase, we also pull a Nginx container. Thanks for pointing this. I guess then that the Nginx of the production server only acts as a kind of reverse proxy to pass requests to the Nginx-Pixel-docker-container.

CircleCI appears as the main actor for the test and construction of Pixel. Could you reflect this in your scheme @thomasdenecker ?

**Comment by jmaupetit** [comment]
> Why the caching of the front-end in CircleCI? Because the scss code changes less than the back-end or because its compilation is very slow?

Using CircleCI cache feature speeds up job execution: if no new front-end dependency has been added, this avoids fetching all dependencies for every build (the slowest step in the front-end building process). Moreover, caching is a way to save job results and use it in another job. This is specifically  how we use it to embed styles in Pixel's container.

> I guess then that the Nginx of the production server only acts as a kind of reverse proxy to pass requests to the Nginx-Pixel-docker-container.

In staging/production, we have three docker containers:

* `db`: the PostgreSQL database
* `web`: Pixel's container
* `proxy`: a NGINX container that serves media + statics and reverse-proxy requests to the gunicorn wsgi server (in Pixel's container) via a unix socket shared in a volume (named `run`).

You have to know that we do not expose the `proxy` container to the internet: there is another NGINX layer that reverse-proxy requests to our `proxy` container.

**Comment by pierrepo** [comment]
> Using CircleCI cache feature speeds up job execution: if no new front-end dependency has been added, this avoids fetching all dependencies for every build (the slowest step in the front-end building process). 

Very good. If I understand correctly we are caching all dependencies installed on top of the basic node Docker container. 
Do we also cache the result of the compilation itself (`scss` -> `css`)? I do not even know if it's possible.

In the production phase and for the `proxy` container, couldn't gunicorn or Django serves itself the static and media files? I thought it was duable.

**Comment by jmaupetit** [comment]
> If I understand correctly we are caching all dependencies installed on top of the basic node Docker container.

Yes!

>  Do we also cache the result of the compilation itself (scss -> css)? I do not even know if it's possible.

Yes! We add the `static` directory to the front-end cache (see https://github.com/Candihub/pixel/blob/master/.circleci/config.yml#L20).

> In the production phase and for the proxy container, couldn't gunicorn or Django serves itself the static and media files? I thought it was duable.

Yes, Django can serve media and statics (as with the development server), but, for performance/security reasons, this is not recommended to do this in production (see https://docs.djangoproject.com/en/1.11/howto/static-files/deployment/).

**Comment by jmaupetit** [comment]
Thx @pierrepo! Note that `yarn` is pre-installed in the `node` container (see [Node official `Dockerfile`](https://github.com/nodejs/docker-node/blob/master/8/Dockerfile#L45)).

**Comment by pierrepo** [comment]
Tell me when you'll be ready that I validate the review.

**Pull request merged**
